# Configuration file for JuliaFormatter.jl
# For more information, see: https://domluna.github.io/JuliaFormatter.jl/stable/config/

whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
short_to_long_function_def = true
long_to_short_function_def = true
whitespace_in_kwargs = false
conditional_to_if = true
separate_kwargs_with_semicolon = true
